# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline: 
  - name: "SpacyNLP"
    model: "model_word2vec"
    case_sensitive: false
  - name: "SpacyTokenizer"                    #custom usepyvi
  - name: "CountVectorsFeaturizer"  
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "EmbeddingIntentClassifier"
  # - name: "SpacyNLP"
  #   model: "vi_model_best"
  #   case_sensitive: false
  # - name: "SpacyTokenizer"
  # - name: "SpacyFeaturizer"
  # - name: "EmbeddingIntentClassifier"
  # - name: "CRFEntityExtractor"
  # - name: "EntitySynonymMapper"
  # - name: "SpacyEntityExtractor"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: KerasPolicy
    epochs: 300
  - name: MappingPolicy
  - name: FormPolicy
