# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
  - name: "SpacyNLP"
    model: "model-final_old"
    case_sensitive: false
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "EmbeddingIntentClassifier"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  # - name: "SpacyNLP"
  #   model: "vi_model_best"
  #   case_sensitive: false
  # - name: "SpacyTokenizer"
  # - name: "SpacyFeaturizer"
  # - name: "EmbeddingIntentClassifier"
  # - name: "CRFEntityExtractor"
  # - name: "EntitySynonymMapper"
  # - name: "SpacyEntityExtractor"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FormPolicy"
